version: "3"
services:
  app:
    command: "tail -f /dev/null"
    image: "node:12"
    ports:
      - "4200:4200"
      - "4201:4201"
      - "9876:9876"
    volumes:
      - "./:/app"
    working_dir: "/app"
